### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by Likenttt** [chencn/ConvertYamlAndProperties#9]

**Comment by Likenttt** [comment]
原来的yml中redis cluster是
```
redis:
  cluster:
    nodes:
      - 127.0.0.1:6379
      - 127.0.0.1:6380

```

最终会被转换成
``
redis.cluster=[127.0.0.1:6379,127.0.0.1:6379]
```
实际上应该写成 redis.cluster.nodes=127.0.0.1:6379,127.0.0.1:6379
